name: Release

on:
  push:
    tags:
      - "*"

jobs:
  api:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Docker login
        run: docker login -u bitmetro -p ${{ secrets.DOCKER_PASSWORD }} docker.io

      - name: Build and push api
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: Dockerfile.api
          tags: bitmetro/phrase-gen-api:${{ github.ref_name }}
          build-args: |
            SCOPE=api
  web:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Docker login
        run: docker login -u bitmetro -p ${{ secrets.DOCKER_PASSWORD }} docker.io

      - name: Build and push web app
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: Dockerfile.web
          tags: bitmetro/phrase-gen-app:${{ github.ref_name }}
          build-args: |
            SCOPE=web
